@extends("app")

@section("customJS")
<script src="/js/Battleship.js"></script>
@stop

@section("content")

<div class="col-sm-3 col-md-2 sidebar">
	<ul class="nav nav-sidebar" id="gamesList">
		<li><a href="#">No Active Games</a></li>
	</ul>
	<br>
</div>

<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<h1>Game <span class="gameID"></span>: <span class="player1ID"></span> vs <span class="player2ID"></span></h1>
	
	<table class="table table-bordered" style="float: left; width: 49%;" id="player1Raw">
		<thead>
			<tr>
				<th class="player1ID">Player 1</th>
				<th>0</th>
				<th>1</th>
				<th>2</th>
				<th>3</th>
				<th>4</th>
				<th>5</th>
				<th>6</th>
				<th>7</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>A</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>B</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>C</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>D</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>E</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>F</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>G</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>H</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
		</tbody>
	</table>
	
	<table class="table table-bordered" style="width: 49%; float: right;" id="player2Raw">
		<thead>
			<tr>
				<th class="player2ID">Player 2</th>
				<th>0</th>
				<th>1</th>
				<th>2</th>
				<th>3</th>
				<th>4</th>
				<th>5</th>
				<th>6</th>
				<th>7</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>A</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>B</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>C</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>D</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>E</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>F</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>G</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
			<tr>
				<td>H</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
				<td>x</td>
			</tr>
		</tbody>
	</table>
</div>

@stop